import csv
import io
import json
from typing import List
from .models import ArchiveProof

def export_proofs_csv(proofs: List[ArchiveProof]) -> str:
    output = io.StringIO()
    writer = csv.writer(output)

    # Header
    writer.writerow([
        "Proof Token",
        "Original URL",
        "Snapshot URL",
        "Provider",
        "HTTP Status",
        "SHA-256 Digest",
        "Submit Timestamp",
        "Verification Status"
    ])

    for p in proofs:
        writer.writerow([
            p.proof_token,
            p.original_url,
            p.snapshot_url,
            p.provider_name,
            p.http_status,
            p.checksum_sha256,
            p.submit_timestamp.isoformat() if p.submit_timestamp else "",
            "VERIFIED" if p.verified else "UNVERIFIED"
        ])

    return output.getvalue()

def export_proofs_json(proofs: List[ArchiveProof]) -> str:
    records = []
    for p in proofs:
        records.append({
            "proof_token": p.proof_token,
            "job_id": p.job_id,
            "original_url": p.original_url,
            "snapshot_url": p.snapshot_url,
            "provider_name": p.provider_name,
            "http_status": p.http_status,
            "checksum_sha256": p.checksum_sha256,
            "submit_timestamp": p.submit_timestamp.isoformat() if p.submit_timestamp else None,
            "verified": p.verified,
            "raw_response_meta": json.loads(p.raw_response_meta) if p.raw_response_meta else {}
        })
    return json.dumps(records, indent=2)

def generate_proof_certificate_html(proof: ArchiveProof) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Proof of Archive Certificate - {proof.proof_token}</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #0f172a; color: #f8fafc; padding: 40px; margin: 0; }}
        .cert-card {{ max-width: 800px; margin: 0 auto; background: #1e293b; border: 2px solid #3b82f6; border-radius: 12px; padding: 32px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }}
        .header {{ text-align: center; border-bottom: 1px solid #334155; padding-bottom: 20px; margin-bottom: 24px; }}
        .header h1 {{ margin: 0; color: #60a5fa; font-size: 26px; }}
        .header p {{ color: #94a3b8; font-size: 14px; margin-top: 6px; }}
        .badge {{ display: inline-block; background: #059669; color: white; padding: 4px 12px; border-radius: 9999px; font-weight: bold; font-size: 12px; }}
        .grid {{ display: grid; grid-template-columns: 140px 1fr; gap: 12px; font-size: 14px; margin-bottom: 24px; }}
        .label {{ font-weight: 600; color: #94a3b8; }}
        .val {{ color: #f8fafc; word-break: break-all; font-family: monospace; }}
        .footer {{ text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #334155; padding-top: 16px; margin-top: 24px; }}
    </style>
</head>
<body>
    <div class="cert-card">
        <div class="header">
            <div class="badge">PERMANENT PROOF RECORD</div>
            <h1>Certificate of Web Archival</h1>
            <p>Proof Token: <strong>{proof.proof_token}</strong></p>
        </div>
        <div class="grid">
            <div class="label">Original Target URL:</div>
            <div class="val">{proof.original_url}</div>

            <div class="label">Snapshot URL:</div>
            <div class="val"><a href="{proof.snapshot_url}" target="_blank" style="color:#60a5fa">{proof.snapshot_url}</a></div>

            <div class="label">Archive Provider:</div>
            <div class="val">{proof.provider_name.upper()}</div>

            <div class="label">HTTP Status Code:</div>
            <div class="val">{proof.http_status} OK</div>

            <div class="label">Cryptographic Hash:</div>
            <div class="val">{proof.checksum_sha256}</div>

            <div class="label">Timestamp (UTC):</div>
            <div class="val">{proof.submit_timestamp.strftime("%Y-%m-%d %H:%M:%S UTC") if proof.submit_timestamp else "N/A"}</div>
        </div>
        <div class="footer">
            Generated by Website Archive Submitter & Automated Backup Repository Engine. Immutable cryptographic record.
        </div>
    </div>
</body>
</html>
"""
